#!/usr/bin/env python3
"""Fetch NetBox values and write them to .env.netbox.

Variable naming is a fixed convention -- no mapping file needed. Any !env
reference in data/*.nac.yaml of the form:

    netbox__<region_slug>__<site_slug>__<vlan_id>__prefix
    netbox__<region_slug>__<site_slug>__<vlan_id>__ipaddress

is resolved by looking up, in NetBox: the prefix for <site_slug>+<vlan_id>
(scoped under <region_slug>), and either its CIDR ("prefix") or the IP
address tagged "gateway" under it ("ipaddress").

<region_slug>/<site_slug> are used verbatim as NetBox slugs, so give
regions/sites underscore-based slugs (e.g. "amsterdam_network_1") instead
of the hyphenated default -- shell variable names can't contain hyphens,
and NetBox's SlugField accepts underscores just as well.

The script discovers which variables to resolve by scanning data/*.nac.yaml
for !env tags matching this pattern -- it does not need to be told about
them separately.

Run manually: `python3 scripts/fetch_netbox_env.py` from the repo root, then
review `git diff .env.netbox` before committing.

Requires NETBOX_URL and NETBOX_TOKEN in the environment (keep these in the
gitignored .env, never in .env.netbox).

NetBox-side prerequisites: each site must belong to the referenced region,
and each prefix must have exactly one IP address object tagged "gateway".
"""
import os
import re
import sys
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
ENV_NETBOX_FILE = REPO_ROOT / ".env.netbox"

VAR_RE = re.compile(r"!env\s+(netbox__\S+)")
FIELDS = ("prefix", "ipaddress")


def find_netbox_vars():
    names = set()
    for path in sorted(DATA_DIR.glob("*.nac.yaml")):
        names.update(VAR_RE.findall(path.read_text()))
    return sorted(names)


def parse_var(var):
    parts = var.split("__")
    if len(parts) != 5 or parts[0] != "netbox":
        sys.exit(
            f"Invalid NetBox env var name {var!r}, expected "
            f"netbox__<region>__<site>__<vlan_id>__<prefix|ipaddress>"
        )
    _, region, site, vlan_id, field = parts
    if field not in FIELDS:
        sys.exit(f"{var!r}: field must be one of {FIELDS}, got {field!r}")
    if not vlan_id.isdigit():
        sys.exit(f"{var!r}: vlan_id segment {vlan_id!r} is not an integer")
    return region, site, int(vlan_id), field


def netbox_get(session, base_url, path, params):
    resp = session.get(f"{base_url}{path}", params=params, timeout=15)
    resp.raise_for_status()
    return resp.json()["results"]


def fetch_prefix(session, base_url, region, site, vlan_id):
    prefixes = netbox_get(
        session,
        base_url,
        "/api/ipam/prefixes/",
        {"vlan_vid": vlan_id, "site": site, "region": region},
    )
    if len(prefixes) != 1:
        sys.exit(
            f"Expected exactly 1 prefix for region={region!r} site={site!r} "
            f"vlan_id={vlan_id}, found {len(prefixes)}"
        )
    return prefixes[0]["prefix"]


def fetch_gateway(session, base_url, prefix_cidr):
    ips = netbox_get(
        session,
        base_url,
        "/api/ipam/ip-addresses/",
        {"parent": prefix_cidr, "tag": "gateway"},
    )
    if len(ips) != 1:
        sys.exit(
            f"Expected exactly 1 IP tagged 'gateway' under prefix "
            f"{prefix_cidr}, found {len(ips)}"
        )
    return ips[0]["address"].split("/")[0]


def main():
    base_url = os.environ.get("NETBOX_URL")
    token = os.environ.get("NETBOX_TOKEN")
    if not base_url or not token:
        sys.exit("NETBOX_URL and NETBOX_TOKEN must be set in the environment")
    base_url = base_url.rstrip("/")

    session = requests.Session()
    session.headers["Authorization"] = f"Token {token}"

    prefix_cache = {}
    entries = {}
    for var in find_netbox_vars():
        region, site, vlan_id, field = parse_var(var)

        cache_key = (region, site, vlan_id)
        if cache_key not in prefix_cache:
            prefix_cache[cache_key] = fetch_prefix(session, base_url, region, site, vlan_id)
        prefix_cidr = prefix_cache[cache_key]

        if field == "prefix":
            entries[var] = prefix_cidr
        else:
            entries[var] = fetch_gateway(session, base_url, prefix_cidr)

    with open(ENV_NETBOX_FILE, "w") as f:
        f.write("# Generated by scripts/fetch_netbox_env.py -- do not hand-edit.\n")
        f.write("# Safe to commit: NetBox-sourced values, not secrets.\n")
        for key in sorted(entries):
            f.write(f"export {key}={entries[key]}\n")

    print(f"Wrote {len(entries)} variables to {ENV_NETBOX_FILE}")


if __name__ == "__main__":
    main()
